/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f8fafc",
        surface: "#ffffff",
        "surface-tint": "#2563eb",
        "secondary-container": "#f1f5f9",
        "surface-dim": "#f8fafc",
        error: "#ef4444",
        "surface-variant": "#f1f5f9",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#f8fafc",
        "surface-container-low": "#ffffff",
        tertiary: "#f59e0b",
        "tertiary-fixed-dim": "#f59e0b",
        "on-primary": "#ffffff",
        "on-background": "#0f172a",
        "on-tertiary-fixed-variant": "#ffffff",
        "on-secondary-fixed": "#1e293b",
        "inverse-on-surface": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "on-secondary-fixed-variant": "#475569",
        "on-primary-container": "#ffffff",
        "surface-container-high": "#ffffff",
        "secondary-fixed-dim": "#cbd5e1",
        "secondary-fixed": "#e2e8f0",
        "outline-variant": "#e2e8f0",
        "on-primary-fixed-variant": "#ffffff",
        "error-container": "#fee2e2",
        "inverse-primary": "#ffffff",
        "primary-fixed": "#dbeafe",
        "on-surface": "#0f172a",
        "primary-container": "#bfdbfe",
        "on-surface-variant": "#64748b",
        "inverse-surface": "#0f172a",
        "on-error": "#ffffff",
        "on-error-container": "#7f1d1d",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#1e293b",
        "surface-container": "#ffffff",
        primary: "#2563eb",
        outline: "#cbd5e1",
        "tertiary-container": "#fef3c7",
        "on-tertiary-fixed": "#78350f",
        "on-primary-fixed": "#1e3a8a",
        secondary: "#64748b",
        "surface-bright": "#ffffff",
        "primary-fixed-dim": "#93c5fd",
        "tertiary-fixed": "#fde68a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontFamily: {
        headline: ["Space_Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
